# Generated by Django 3.0.4 on 2020-04-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prjct_description', models.CharField(max_length=100)),
                ('Ranks', models.CharField(choices=[('Acd', 'Academic'), ('Carr', 'Career')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('Bio_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=30)),
                ('Marks_GPA', models.FloatField(max_length=10)),
                ('Degree', models.CharField(max_length=20)),
                ('Bio_edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio_data')),
            ],
        ),
    ]
