# Generated by Django 3.0.4 on 2020-04-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='Marks_GPA',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prjct_description', models.CharField(max_length=100)),
                ('Bio_personal_prjct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio_data')),
            ],
        ),
    ]
