# Generated by Django 3.0.4 on 2020-04-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200420_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Bio_personal_prjct',
            new_name='Bio_prjct',
        ),
    ]
