# Generated by Django 3.0.4 on 2020-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200423_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='Institute_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
