# Generated by Django 3.0.4 on 2020-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200425_1525'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bio_data',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='pinned_tweet'),
        ),
    ]
