# Generated by Django 3.0.4 on 2020-04-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20200426_1644'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bio_data',
            name='pinned_tweet',
        ),
        migrations.AddConstraint(
            model_name='bio_data',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='name_email'),
        ),
    ]
