# Generated by Django 3.0.4 on 2020-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20200426_1645'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bio_data',
            name='name_email',
        ),
        migrations.AddConstraint(
            model_name='bio_data',
            constraint=models.UniqueConstraint(fields=('name',), name='name_email'),
        ),
    ]
